name: Build and Deploy Sileo Repo to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'debs/**'  # 监听 debs 目录下的所有文件变化

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install required tools
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Generate Packages files (recursive)
        run: |
          mkdir -p dist
          # 递归扫描所有子目录中的deb包
          dpkg-scanpackages -r debs /dev/null > Packages
          # 生成压缩版本
          bzip2 -c Packages > Packages.bz2
          gzip -c Packages > Packages.gz

          # 生成包含所有版本的Release文件
          cat << EOF > Release
Origin: 你看，又急
Label: 贾队长
Suite: stable
Version: 1.0
Codename: qtz
Architectures: iphoneos-arm64 iphoneos-arm64e
Components: main
Description: 自用插件分享，有问题请卸载！！！
$(dpkg-scanpackages --arch arm64 --arch arm64e debs /dev/null | grep -v '^$' | sed '1d' | awk '{print "Package: "$2"\nVersion: "$3"\nArchitecture: "$1"\nMaintainer: "$4"\nDescription: "$5}')
EOF

      - name: Commit and push updated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/Packages* dist/Release
          git commit -m "Update repo metadata" || echo "No changes to commit"
          git push origin main || echo "Push failed"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: ./dist
